FROM quay.io/airshipit/nova:2024.1-ubuntu_jammy

RUN cp /usr/share/spice-html5/spice_auto.html /usr/share/spice-html5/spice_auto_bak.html
COPY nova_spiceproxy/spice_auto.html /usr/share/spice-html5/spice_auto.html